# Generated by Django 2.2.12 on 2020-05-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_details', '0004_auto_20200508_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contest_details',
        ),
    ]
