# Generated by Django 2.2.12 on 2020-05-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest_details', '0005_delete_contest_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_user_website_name', models.CharField(max_length=20)),
                ('registered_user_website_handler_link', models.URLField()),
                ('registered_user_website_image', models.ImageField(upload_to='contest')),
                ('registerd_user_website_best_rating', models.IntegerField()),
            ],
        ),
    ]
