# Generated by Django 2.2.12 on 2020-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_details', '0006_contest_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_detail',
            name='registered_user_password',
            field=models.CharField(default='please enter the password', max_length=20),
        ),
    ]
