# Generated by Django 2.2.12 on 2020-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_details', '0008_contest_detail_registerd_user_website_userhandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='stopstalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_user_password', models.CharField(max_length=20)),
                ('registered_user_website_image', models.ImageField(upload_to='contest')),
            ],
        ),
    ]
