# Generated by Django 2.2.12 on 2020-05-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_details', '0009_stopstalk'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopstalk',
            name='stopstalk_profile',
            field=models.URLField(default='http://please_enter_your_handler'),
        ),
    ]
