# Generated by Django 2.2.12 on 2020-05-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_details', '0010_stopstalk_stopstalk_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stopstalk',
        ),
    ]
