# Generated by Django 2.2.12 on 2020-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment_detail',
            name='registered_user_languages_known',
            field=models.TextField(blank=True, null=True),
        ),
    ]
