# Generated by Django 2.2.12 on 2020-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stopstalk_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_user_password', models.CharField(max_length=20)),
                ('registered_user_website_image', models.ImageField(upload_to='contest')),
                ('stopstalk_profile', models.URLField(default='http://please_enter_your_handler')),
            ],
        ),
    ]
