# Generated by Django 2.2.12 on 2020-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user_detail',
            name='registered_uesr_name',
            field=models.CharField(max_length=50,primary_key=False),
        ),
        migrations.AlterField(
            model_name='registered_user_detail',
            name='registered_uesr_password',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
