# Generated by Django 2.2.12 on 2020-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200508_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_detail',
            name='registered_uesr_bio',
            field=models.CharField(default="You haven't entered any detail ", max_length=200),
        ),
    ]
