# Generated by Django 2.2.12 on 2020-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registered_user_detail_registered_uesr_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_detail',
            name='registered_uesr_email',
            field=models.EmailField(default="You_Haven't_entered_mail@pleaseDo.com", max_length=254),
        ),
    ]
