# Generated by Django 2.2.12 on 2020-05-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_registered_user_detail_registered_uesr_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user_detail',
            name='registered_uesr_linkedin',
            field=models.URLField(default="You_Haven't_entered_linkedin_id@pleaseDo.com", max_length=254),
        ),
    ]
