# Generated by Django 2.2.12 on 2020-05-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_registered_user_detail_registered_uesr_accomplishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user_detail',
            name='registered_uesr_accomplishment',
            field=models.TextField(default='No enteries made'),
        ),
    ]
