# Generated by Django 2.2.12 on 2020-05-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200509_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_detail',
            name='registered_uesr_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_photo'),
        ),
    ]
